name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Exact steps required to reproduce the issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System and version details.
      placeholder: |
        OS:
        Architecture:
        Version / commit:
        Installation method:

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Relevant logs or error output.
      render: shell
